version: "2"
services:
  debug:
    image: busybox
    command: sh
    volumes:
      - data:/data/plain
      - encrypted-data:/data/encrypted

  sut:
    build: .
    entrypoint: /run-test.sh
    volumes:
      - data:/data/plain
      - encrypted-data:/data/encrypted
      - ./run-test.sh:/run-test.sh
    environment:
      - DEBUG=${BASH_DEBUG}
      - LOG_DEBUG=${DEBUG}
      - GPG_PASSPHRASE=topsecret
      - AWS_ACCESS_KEY=${ACCESS_KEY}
      - AWS_SECRET_KEY=${SECRET_KEY}
      - AWS_S3_BUCKET=${BUCKET}
      - AWS_S3_BUCKET_PATH=/backups/
      - SOURCE_REMOVE_PLAIN=1
      - SOURCE_FILE_MODIFIED_MINUTES_AGO=0
      - SOURCE_FILE_PATTERN=*.txt

volumes:
  data:
  encrypted-data:
